# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/artificial-blogging',
                'doc_host': 'https://gabrieli.github.io',
                'git_url': 'https://github.com/gabrieli/artificial-blogging',
                'lib_path': 'artificial_blogging'},
  'syms': {'artificial_blogging.core': {'artificial_blogging.core.foo': ('core.html#foo', 'artificial_blogging/core.py')}}}
